use_frameworks!

target 'ReusableViews_Example' do
  pod 'ReusableViews', :path => '../'
  pod 'SwiftLint'
end

target 'ReusableViews_Tests' do
  pod 'ReusableViews', :path => '../'
  pod 'Quick'
  pod 'Nimble'
end
