use_frameworks!

target 'ReusableViews_Example' do
  pod 'ReusableViews', :path => '../'
  pod 'SwiftLint'
end

target 'ReusableViews_Tests' do
  pod 'ReusableViews', :path => '../'
  pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
end
